spring:
  profiles:
    #指定缓存类型
    include: common

dingding:
  base-url: ${DINGTALK_BASE_URL:https://oapi.dingtalk.com}
  app-key: ${DINGTALK_ACCESS_TOKEN:} # https://open.dingtalk.com/document/development/how-to-call-apis?spm=ding_open_doc.document.0.0.15d327e2IajId6
  app-sercret: ${DINGTALK_ACCESS_TOKEN:} 
  templateId: 0fd78661-b1b0-4904-9426-ffcaa4754496 # https://open-dev.dingtalk.com/fe/im?spm=ding_open_doc.document.0.0.761634e6WdyAuo&hash=%23%2Fgroup%2Flist#/group/list
  robotCode: dingmwjw3fkvapwczxnz
