spring:
  profiles:
    #指定缓存类型
    include: common

dingtalk:
  base-url: ${DINGTALK_BASE_URL:https://oapi.dingtalk.com}
  access-token: ${DINGTALK_ACCESS_TOKEN:} # https://open-dev.dingtalk.com/?spm=ding_open_doc.document.0.0.377276e0bLlGb9&hash=%23%2F#/
  templateId: 2ce1482d-2b4c-4c85-9b81-b80a59584302 # https://open-dev.dingtalk.com/fe/im?spm=ding_open_doc.document.0.0.761634e6WdyAuo&hash=%23%2Fgroup%2Flist#/group/list
